version: "3.7"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    expose:
      - 9000
      - 9001
#    ports:
#      - 9001:9001
#      - 9000:9000
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio12345}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio12345}
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    networks:
      - minio

  nginx:
    build: ./nginx
    container_name: minio-nginx
    ports:
      - 8003:80
    depends_on:
      - minio
    networks:
      - minio

volumes:
  minio_data:
    name: minio_data

networks:
  minio: