version: "3.7"
services:

  audio-speech-detection:
    build: ./audio-speech-detection
    container_name: audio-speech-detection
    expose:
      - 660
    environment:
      - ENDPOINT=/audio-speech-detection
      - MINIO_URL=${MINIO_URL:-minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minio123}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minio123}
    command: gunicorn --workers=2 --threads 1 -b 0.0.0.0:660 entry_point:app --worker-class sync

  minio:
    image: minio/minio:latest
    expose:
      - 9000
      - 9001
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio12345}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio12345}
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    depends_on:
      - audio-speech-detection

volumes:
  minio_data:
    name: minio_data

