version: '3.7'

services:

  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    expose:
      - "9000"
      - "9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio12345}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio12345}
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9000:9000
      - 9001:9001
    depends_on:
      - minio

## For custom volumes replace with volume driver configuration.
volumes:
  minio_data:
    name: minio_data
